import type { Metadata } from "next";
import { Inter, Manrope } from "next/font/google";
// @ts-ignore: CSS module type declarations missing in current TypeScript setup
import "./globals.css";
import { AuthProvider } from "./providers";
import { Toaster } from "sonner";
import SessionGuard from "@/components/SessionGuard";
import { SpeedInsights } from "@vercel/speed-insights/next";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Instroom | Simplify your influencer marketing workflow",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${manrope.variable} antialiased`}
        suppressHydrationWarning
      >
        <AuthProvider>
          <SessionGuard>
            {children}
          </SessionGuard>
        </AuthProvider>
        <Toaster />
        <SpeedInsights />
      </body>
    </html>
  );
}